version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: db-queries
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_here
      - MYSQL_DATABASE=employees
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./db/employees.sql:/docker-entrypoint-initdb.d/employees.sql
      - ./db/test_db:/test_db
    ports:
      - "127.0.0.1:3306:3306"

volumes:
  mariadb_data: